services:
  app:
    build:
      context: ./app
      target: dev
    environment:
      REACT_APP_BASE_URL: ${REACT_APP_BASE_URL}
      WATCHPACK_POLLING: true # hotswap, remove on prod
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
  mysql:
    image: mysql:9.0.1
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db:/var/lib/mysql
volumes:
  db: